version: '3.7'
services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.6.1
    ports:
      - "8081:8081"
    volumes:
      - ./conf/server:/opt/spire/conf/server
  workload:
    image: ghcr.io/spiffe/spire-agent:1.6.1
    ports:
      - "8080:8080"
    depends_on:
      - spire-server
    volumes:
      - ./conf/agent:/opt/spire/conf/agent
